=== anibal-corral/SitioInstrumentosMTI/entrega/parte 1/establecimiento.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT establecimiento (nombre,rut,ubicacion,telefono,horario)>
<!ATTLIST establecimiento
  xmlns CDATA #FIXED ''
  idEstablecimiento CDATA #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre
  xmlns CDATA #FIXED ''>

<!ELEMENT rut (numero,dv)>
<!ATTLIST rut
  xmlns CDATA #FIXED ''>

<!ELEMENT ubicacion (pais,region,ciudad,comuna,calle,numero,coordenada)>
<!ATTLIST ubicacion
  xmlns CDATA #FIXED ''>

<!ELEMENT telefono (codigoPais,prefijo,numero)>
<!ATTLIST telefono
  xmlns CDATA #FIXED ''>

<!ELEMENT horario (#PCDATA)>
<!ATTLIST horario
  xmlns CDATA #FIXED ''>

<!ELEMENT dv (#PCDATA)>
<!ATTLIST dv
  xmlns CDATA #FIXED ''>

<!ELEMENT pais (#PCDATA)>
<!ATTLIST pais
  xmlns CDATA #FIXED ''>

<!ELEMENT region (#PCDATA)>
<!ATTLIST region
  xmlns CDATA #FIXED ''>

<!ELEMENT ciudad (#PCDATA)>
<!ATTLIST ciudad
  xmlns CDATA #FIXED ''>

<!ELEMENT comuna (#PCDATA)>
<!ATTLIST comuna
  xmlns CDATA #FIXED ''>

<!ELEMENT calle (#PCDATA)>
<!ATTLIST calle
  xmlns CDATA #FIXED ''>

<!ELEMENT coordenada (latitud,longitud)>
<!ATTLIST coordenada
  xmlns CDATA #FIXED ''>

<!ELEMENT codigoPais (#PCDATA)>
<!ATTLIST codigoPais
  xmlns CDATA #FIXED ''>

<!ELEMENT prefijo (#PCDATA)>
<!ATTLIST prefijo
  xmlns CDATA #FIXED ''>

<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud
  xmlns CDATA #FIXED ''>

<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud
  xmlns CDATA #FIXED ''>

<!ELEMENT numero (#PCDATA)>
<!ATTLIST numero
  xmlns CDATA #FIXED ''>

=== anibal-corral/SitioInstrumentosMTI/entrega/parte 1/establecimiento.xml
<?xml version="1.0"?>
<!DOCTYPE establecimiento SYSTEM "establecimiento.dtd">
<establecimiento idEstablecimiento="3">
  <nombre>Tienda USM</nombre>
  <rut>
	<numero>98765000</numero>
	<dv>0</dv>
  </rut>
  <ubicacion>
    <pais>CHILE</pais>
    <region>Metropolitana</region>
    <ciudad>SANTIAGO</ciudad>
    <comuna>Vitacura</comuna>
    <calle>Avenida Santa Maria</calle>
    <numero>6400</numero>
	<coordenada>
		<latitud>-33.3775228</latitud>
		<longitud>-70.5774312</longitud>
	</coordenada>
  </ubicacion>
  <telefono>
	<codigoPais>56</codigoPais>
	<prefijo>32</prefijo>
	<numero>2654678</numero>
  </telefono>
  <horario>Sin informaci√≥n</horario>
</establecimiento>
