=== anibal-corral/SitioInstrumentosMTI/entrega/parte 1/inventario.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT inventario (establecimiento,listaProductos)>
<!ATTLIST inventario
  xmlns CDATA #FIXED ''>

<!ELEMENT establecimiento EMPTY>
<!ATTLIST establecimiento
  xmlns CDATA #FIXED ''
  idEstablecimiento CDATA #REQUIRED>

<!ELEMENT listaProductos (producto)+>
<!ATTLIST listaProductos
  xmlns CDATA #FIXED ''>

<!ELEMENT producto (cantidad,precio,moneda,estado,fechaIngreso,
                    fechaActualizacion)>
<!ATTLIST producto
  xmlns CDATA #FIXED ''
  idProducto CDATA #REQUIRED>

<!ELEMENT cantidad (#PCDATA)>
<!ATTLIST cantidad
  xmlns CDATA #FIXED ''>

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio
  xmlns CDATA #FIXED ''>

<!ELEMENT moneda (#PCDATA)>
<!ATTLIST moneda
  xmlns CDATA #FIXED ''>

<!ELEMENT estado (#PCDATA)>
<!ATTLIST estado
  xmlns CDATA #FIXED ''>

<!ELEMENT fechaIngreso (#PCDATA)>
<!ATTLIST fechaIngreso
  xmlns CDATA #FIXED ''>

<!ELEMENT fechaActualizacion (#PCDATA)>
<!ATTLIST fechaActualizacion
  xmlns CDATA #FIXED ''>

=== anibal-corral/SitioInstrumentosMTI/entrega/parte 1/inventario.xml
<?xml version="1.0"?>
<!DOCTYPE inventario SYSTEM "inventario.dtd">
<inventario>
	<establecimiento idEstablecimiento="3"/>
	<listaProductos>
		<producto idProducto="10">
			<cantidad>4</cantidad>
			<precio>5000</precio>
			<moneda>USD</moneda>
			<estado>DISPONIBLE</estado>
			<fechaIngreso>2017-03-27</fechaIngreso>
			<fechaActualizacion>2017-03-29</fechaActualizacion>
		</producto>
		<producto idProducto="21">
			<cantidad>5</cantidad>
			<precio>2500</precio>
			<moneda>USD</moneda>
			<estado>DISPONIBLE</estado>
			<fechaIngreso>2017-03-27</fechaIngreso>
			<fechaActualizacion>2017-03-28</fechaActualizacion>
		</producto>
		<producto idProducto="8">
			<cantidad>6</cantidad>
			<precio>3000</precio>
			<moneda>USD</moneda>
			<estado>DISPONIBLE</estado>
			<fechaIngreso>2017-03-27</fechaIngreso>
			<fechaActualizacion>2017-03-27</fechaActualizacion>
		</producto>
	</listaProductos>
</inventario>
