=== anibal-corral/SitioInstrumentosMTI/entrega/parte 1/producto.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT producto (codigo,nombre,descripcion,marca,modelo,
                    listaCategorias,listaCaracteristicas)>
<!ATTLIST producto
  xmlns CDATA #FIXED ''
  idProducto CDATA #REQUIRED>

<!ELEMENT codigo (#PCDATA)>
<!ATTLIST codigo
  xmlns CDATA #FIXED ''>

<!ELEMENT descripcion (#PCDATA)>
<!ATTLIST descripcion
  xmlns CDATA #FIXED ''>

<!ELEMENT marca (#PCDATA)>
<!ATTLIST marca
  xmlns CDATA #FIXED ''>

<!ELEMENT modelo (#PCDATA)>
<!ATTLIST modelo
  xmlns CDATA #FIXED ''>

<!ELEMENT listaCategorias (categoria)>
<!ATTLIST listaCategorias
  xmlns CDATA #FIXED ''>

<!ELEMENT listaCaracteristicas (caracteristica)+>
<!ATTLIST listaCaracteristicas
  xmlns CDATA #FIXED ''>

<!ELEMENT categoria (#PCDATA)>
<!ATTLIST categoria
  xmlns CDATA #FIXED ''>

<!ELEMENT caracteristica (nombre,valor)>
<!ATTLIST caracteristica
  xmlns CDATA #FIXED ''>

<!ELEMENT valor (#PCDATA)>
<!ATTLIST valor
  xmlns CDATA #FIXED ''>

<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre
  xmlns CDATA #FIXED ''>

=== anibal-corral/SitioInstrumentosMTI/entrega/parte 1/producto.xml
<?xml version="1.0"?>
<!DOCTYPE producto SYSTEM "producto.dtd">
<producto idProducto="10">
	<codigo>737383</codigo>
	<nombre>Guitarra eléctrica GRX22 color candy apple (CA)  Ibanez</nombre>
	<descripcion>Guitarra eléctrica Marca Ibanez modelo GRX22. Una guitarra no tiene que costar una fortuna para tener un buen sonido, es el caso de la serie GRX de Ibanez, fue desarrollada para los músicos que desean la calidad de esta marca, pero a un precio asequible.</descripcion>
	<marca>Ibanez</marca>
	<modelo>GRX22</modelo>
	<listaCategorias>
		<categoria>Guitarra eléctrica</categoria>
	</listaCategorias>
	<listaCaracteristicas>
		<caracteristica>
			<nombre>ESCALA</nombre>
			<valor>25.5 pulgadas</valor>
		</caracteristica>
		<caracteristica>
			<nombre>NÚMERO DE CUERDAS</nombre>
			<valor>6</valor>
		</caracteristica>
		<caracteristica>
			<nombre>COLOR</nombre>
			<valor>Candy Apple (CA)</valor>
		</caracteristica>
		<caracteristica>
			<nombre>MATERIAL NECK</nombre>
			<valor>Maple</valor>
		</caracteristica>
		<caracteristica>
			<nombre>MATERIAL CUERPO</nombre>
			<valor>Basswood</valor>
		</caracteristica>
	</listaCaracteristicas>
</producto>
