=== anibal-corral/SitioInstrumentosMTI/entrega/parte 1/venta.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT venta (establecimiento,cliente,items,montoTotal,monedaVenta,
                 fechaVenta,medioPago)>
<!ATTLIST venta
  xmlns CDATA #FIXED ''
  idVenta CDATA #REQUIRED>

<!ELEMENT establecimiento EMPTY>
<!ATTLIST establecimiento
  xmlns CDATA #FIXED ''
  idEstablecimiento CDATA #REQUIRED>

<!ELEMENT cliente (rut,nombres,apellidoPaterno,apellidoMaterno)>
<!ATTLIST cliente
  xmlns CDATA #FIXED ''
  idCliente CDATA #REQUIRED>

<!ELEMENT items (producto)>
<!ATTLIST items
  xmlns CDATA #FIXED ''>

<!ELEMENT montoTotal (#PCDATA)>
<!ATTLIST montoTotal
  xmlns CDATA #FIXED ''>

<!ELEMENT monedaVenta (#PCDATA)>
<!ATTLIST monedaVenta
  xmlns CDATA #FIXED ''>

<!ELEMENT fechaVenta (#PCDATA)>
<!ATTLIST fechaVenta
  xmlns CDATA #FIXED ''>

<!ELEMENT medioPago (#PCDATA)>
<!ATTLIST medioPago
  xmlns CDATA #FIXED ''>

<!ELEMENT rut (numero,dv)>
<!ATTLIST rut
  xmlns CDATA #FIXED ''>

<!ELEMENT nombres (#PCDATA)>
<!ATTLIST nombres
  xmlns CDATA #FIXED ''>

<!ELEMENT apellidoPaterno (#PCDATA)>
<!ATTLIST apellidoPaterno
  xmlns CDATA #FIXED ''>

<!ELEMENT apellidoMaterno (#PCDATA)>
<!ATTLIST apellidoMaterno
  xmlns CDATA #FIXED ''>

<!ELEMENT producto (cantidad,nombre,precio,moneda)>
<!ATTLIST producto
  xmlns CDATA #FIXED ''
  idProducto CDATA #REQUIRED>

<!ELEMENT numero (#PCDATA)>
<!ATTLIST numero
  xmlns CDATA #FIXED ''>

<!ELEMENT dv (#PCDATA)>
<!ATTLIST dv
  xmlns CDATA #FIXED ''>

<!ELEMENT cantidad (#PCDATA)>
<!ATTLIST cantidad
  xmlns CDATA #FIXED ''>

<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre
  xmlns CDATA #FIXED ''>

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio
  xmlns CDATA #FIXED ''>

<!ELEMENT moneda (#PCDATA)>
<!ATTLIST moneda
  xmlns CDATA #FIXED ''>

=== anibal-corral/SitioInstrumentosMTI/entrega/parte 1/venta.xml
<?xml version="1.0"?>
<!DOCTYPE venta SYSTEM "venta.dtd">
<venta idVenta="10">
	<establecimiento idEstablecimiento="3"/>
	<cliente idCliente="7">
		<rut>
			<numero>18765000</numero>
			<dv>0</dv>
		</rut>
		<nombres>JOSE LUIS</nombres>
		<apellidoPaterno>GUERRERO</apellidoPaterno>
		<apellidoMaterno>DIAZ</apellidoMaterno>
	</cliente>
	<items>
		<producto idProducto="10">
			<cantidad>1</cantidad>
			<nombre>Guitarra el√©ctrica GRX22 color candy apple (CA)  Ibanez</nombre>
			<precio>5000</precio>
			<moneda>USD</moneda>
		</producto>
	</items>
	<montoTotal>5000</montoTotal>
	<monedaVenta>USD</monedaVenta>
	<fechaVenta>2017-03-27</fechaVenta>
	<medioPago>EFECTIVO</medioPago>
</venta>
